import { Book, TranslationSet } from './types';

export const ACF_2007_API_URL = 'https://bible-api.com';
export const ACF_2011_API_URL = 'https://www.abibliadigital.com.br/api';

export const translations: { en: TranslationSet; pt: TranslationSet } = {
  en: {
    studyBible: 'Biblicist Study Bible',
    version: 'Version',
    book: 'Book',
    chapter: 'Chapter',
    kjv1769: 'KJV 1769 (English)',
    acf2011: 'ACF 2011 (Português)',
    acf2007: 'ACF 2007 (Português)',
    askAQuestion: 'Ask a Question',
    thinking: 'Thinking...',
    askToBegin: 'Ask a Bible question to get a Bible answer or choose a specific passage to study, from the drop-down menu below.',
    chatPlaceholder: 'Type here.',
    fetchError: 'An unknown error occurred.',
    fetchChapterError: (message: string) => `Failed to fetch chapter: ${message}`,
    newChat: 'New Chat',
    tooltipSwitchToEnglish: 'Switch to English',
    tooltipSwitchToPortuguese: 'Switch to Portuguese',
    tooltipNewChat: 'Start a new conversation',
    tooltipSubmitQuestion: 'Ask question',
    tooltipExpandCommentary: 'Show commentary',
    tooltipCollapseCommentary: 'Hide commentary',
    toggleCommentaryTranslation: 'Commentary PT/EN',
    tooltipTranslateCommentary: 'Translate all visible commentary',
    acfKjvVariations: 'ACF/KJV Variations',
    tooltipAcfKjvVariations: 'Show a detailed explanation of the translation difference',
    minimize: 'Minimize',
    oldTestament: 'Old Testament',
    newTestament: 'New Testaments',
    tooltipPreviousChapter: 'Previous Chapter',
    tooltipNextChapter: 'Next Chapter',
    ariaGoToSelector: 'Go to book and chapter selection',
    aboutTitle: 'About this Study Bible',
    aboutContentPart1: 'The Biblicist Study Bible is a ministerial arm of the ',
    aboutContentLink: 'Instituto Bíblico Batista Independente (meuIBBI.com)',
    aboutContentPart2: '. This resource is designed to help anyone study the Bible from a purely biblicist perspective, taking the text literally and holding in high regard its accuracy, purity, power, and preservation. To achieve this, it makes use of artificial intelligence to limit its commentary to an analysis and synthesis of the Bible itself. While this approach means commentary takes longer to load than pre-written resources, it helps keep the user connected directly to the text, instead of being turned to teachings imposed upon it. This tool\'s greatest strength is seeking to avoid external theological structures, readily admitting when passages are unclear or difficult for the finite human mind to fully comprehend. However, just as a human writer can make mistakes, so can AI. It is imperative that the user continues to study the biblical text for himself, recognizing the need to study not only individual verses but also the Bible as a whole.',
    commonThemes: 'Common Themes',
    tooltipToggleCommonThemes: 'Show common sermon themes from this chapter',
    commonThemesTitle: 'Common Themes in This Chapter',
    translateThemes: 'Translate Themes',
    summary: 'Summary',
    tooltipToggleSummary: 'Show chapter summary and stats',
    summaryTitle: 'Chapter Summary',
    bookSummaryHeading: 'Book Summary',
    chapterSummaryHeading: 'Chapter Summary',
    chapterStatsHeading: 'Chapter Stats',
    translateSummary: 'Translate Summary',
    tooltipCopy: 'Copy to clipboard',
    tooltipPrint: 'Print',
    tooltipPdf: 'Download as PDF',
    copied: 'Copied!',
    translateConversation: 'Translate Conversation',
    tooltipTranslateConversation: 'Translate this conversation',
    wordDefinitionTitle: (word, verseRef) => `Definition of "${word}" in ${verseRef}`,
    modernDefinitionHeading: 'Modern Definition',
    originalLangDefinitionHeading: (langWord) => `Original Language: ${langWord}`,
    archaicUsageNoteHeading: 'Note on Archaic Usage',
    translateDefinition: 'Translate Definition',
    retryGeneration: 'Retry',
    simplifyCommentary: 'Simplify Text',
    revertCommentary: 'Original Text',
    tooltipSimplifyCommentary: 'Rewrite this commentary in simpler language',
    tooltipRevertCommentary: 'Revert to the original, more detailed commentary',
    crossReferencesHeading: 'Cross-References',
    crossRefFetchError: 'Could not load reference.',
    showCrossRefs: 'Show Cross-References',
    hideCrossRefs: 'Hide Cross-References',
    tooltipShowCrossRefs: 'Generate and show cross-references for this verse',
    tooltipHideCrossRefs: 'Hide the cross-references for this verse',
    viewReading: 'Reading',
    tooltipViewReading: 'Default reading view',
    viewOutline: 'Outline',
    tooltipViewOutline: 'Show chapter outline headings',
    viewCommentary: 'Commentary',
    tooltipViewCommentary: 'Show full commentary for every verse',
    viewSimplified: 'Simplified',
    tooltipViewSimplified: 'Show simplified commentary for every verse',
    moreActions: 'More Actions',
    generatingCommentary: 'Generating commentary',
    generatingCrossRefs: 'Generating cross-references',
    passageSelection: 'Passage Selection',
    godsWord: "God's Word",
    view: "View",
    resources: "Resources",
    sermonEditor: "Sermon Outline Builder",
    study: "Study",
    sermon: "Sermon",
    sermonBuilder: {
      sermonType: 'Sermon Type',
      sermonTypes: {
        general: 'General Sermon',
        expositional: 'Expositional Sermon',
        textual: 'Textual Sermon',
        topical: 'Topical Sermon',
      },
      title: 'Title',
      titleTopical: 'Sermon Topic / Title',
      bibleText: 'Bible Text',
      bibleTextExpositional: 'Main Passage for Exposition',
      bibleTextTextual: 'Sermon Text (e.g., 1-2 verses)',
      introduction: 'Introduction',
      thesis: 'Thesis (Main Truth or Big Idea)',
      thesisExpositional: 'Proposition / Big Idea from Passage',
      thesisTextual: 'Proposition from Text',
      thesisTopical: 'Proposition / Main Statement about Topic',
      point: 'Supporting Point',
      pointExpositional: 'Main Point from Passage',
      pointTextual: 'Main Point from Text',
      pointTopical: 'Main Point about the Topic',
      pointExplanation: 'Explanation',
      scripture: 'Supporting Scripture(s)',
      illustration: 'Illustration',
      conclusion: 'Conclusion',
      verdict: 'Verdict (Application, Invitation, Appeal)',
      sermonBody: 'Sermon Body',
      sermonBodyDescription: 'Add supporting points, scriptures, and illustrations in any order.',
      addItem: 'Add Item',
      generateOutline: 'Generate Outline',
      generatedOutline: 'Generated Outline',
      clearAll: 'Clear All',
      clearAllConfirmation: {
        title: 'Clear Sermon Inputs?',
        message: 'This will erase all content from the sermon builder fields. This action cannot be undone.',
        confirm: 'Clear',
        cancel: 'Keep',
      },
      tooltipAddItem: (type: string) => `Add ${type}`,
      tooltipRemoveItem: 'Remove this item',
      tooltipMoveUp: 'Move item up',
      tooltipMoveDown: 'Move item down',
      fetchAndExpandAll: 'Fetch and expand all verse references',
      expandFetchedOnly: 'Include only pre-fetched verse text',
      fetchVerses: 'Fetch Verses',
      fetchedVerseText: 'Fetched Verse Text',
      disableSermonColors: 'Disable Colors',
      help: {
        title: 'Sermon Outline Builder Guide',
        intro: 'This tool helps you structure your sermon based on common preaching methods. Here\'s how to use it:',
        step1: '1. Choose Sermon Type: Select the sermon style you want to build from the dropdown. "General Sermon" is a flexible default.',
        step2: '2. Fill in the Fields: Add your title, main scripture, introduction, key points, and conclusion into the corresponding fields.',
        step3: '3. Add Body Items: Use the "+ Add Item" buttons to structure the body of your sermon with supporting points, scripture references, and illustrations.',
        step4: '4. Generate Outline: When you\'re ready, click "Generate Outline." You can choose to automatically fetch and include the full text for all scripture references in your outline.',
        sermonTypesTitle: 'Understanding Sermon Types',
        types: {
          general: {
            title: 'General Sermon',
            desc: 'A flexible, all-purpose structure suitable for most messages.'
          },
          expositional: {
            title: 'Expositional Sermon',
            desc: 'Derives its main points and structure directly from a single, larger passage of Scripture. The goal is to expose the meaning of that specific text.'
          },
          textual: {
            title: 'Textual Sermon',
            desc: 'Takes its main points from a shorter text (typically 1-2 verses). The sermon develops these points, often drawing support from other parts of the Bible.'
          },
          topical: {
            title: 'Topical Sermon',
            desc: 'Starts with a subject (e.g., Faith, Prayer) and uses various scriptures from across the Bible to explore that topic.'
          }
        }
      }
    },
    wordCounts: 'Word Counts',
    wordCountFromTranslation: '(from current translation)',
    versesSelected: (count: number) => `${count} verse${count === 1 ? '' : 's'} selected`,
    copySelection: 'Copy Selection',
    copiedSelection: 'Copied!',
    deselectAll: 'Deselect All',
  },
  pt: {
    studyBible: 'Bíblia de Estudo Biblicista',
    version: 'Versão',
    book: 'Livro',
    chapter: 'Capítulo',
    kjv1769: 'KJV 1769 (Inglês)',
    acf2011: 'ACF 2011 (Português)',
    acf2007: 'ACF 2007 (Português)',
    askAQuestion: 'Faça uma Pergunta',
    thinking: 'Pensando...',
    askToBegin: 'Faça uma pergunta bíblica para obter uma resposta bíblica ou escolha uma passagem específica para estudar, no menu suspenso abaixo.',
    chatPlaceholder: 'Digite aqui.',
    fetchError: 'Ocorreu um erro desconhecido.',
    fetchChapterError: (message: string) => `Falha ao buscar o capítulo: ${message}`,
    newChat: 'Nova Conversa',
    tooltipSwitchToEnglish: 'Mudar para Inglês',
    tooltipSwitchToPortuguese: 'Mudar para Português',
    tooltipNewChat: 'Comece uma nova conversa',
    tooltipSubmitQuestion: 'Faça uma pergunta',
    tooltipExpandCommentary: 'Mostrar comentário',
    tooltipCollapseCommentary: 'Esconder comentário',
    toggleCommentaryTranslation: 'Commentary PT/EN',
    tooltipTranslateCommentary: 'Traduzir todo o comentário visível',
    acfKjvVariations: 'Variações ACF/KJV',
    tooltipAcfKjvVariations: 'Mostrar uma explicação detalhada da diferença de tradução',
    minimize: 'Minimizar',
    oldTestament: 'Antigo Testamento',
    newTestament: 'Novo Testamento',
    tooltipPreviousChapter: 'Capítulo Anterior',
    tooltipNextChapter: 'Próximo Capítulo',
    ariaGoToSelector: 'Ir para a seleção de livro e capítulo',
    aboutTitle: 'Sobre esta Bíblia de Estudo',
    aboutContentPart1: 'A Bíblia de Estudo Biblicista é um braço ministerial do ',
    aboutContentLink: 'Instituto Bíblico Batista Independente (meuibbi.com)',
    aboutContentPart2: '. Este recurso foi projetado para ajudar qualquer pessoa a estudar a Bíblia de uma perspectiva puramente biblicista, levando o texto literalmente e tendo em alta conta sua precisão, pureza, poder e preservação. Para alcançar isso, ele utiliza inteligência artificial para limitar seus comentários a uma análise e síntese da própria Bíblia. Embora essa abordagem signifique que o comentário leva mais tempo para carregar do que os recursos pré-escritos, ela ajuda a manter o usuário conectado diretamente ao texto, em vez de direcioná-lo a ensinamentos impostos sobre ele. A maior força desta ferramenta é buscar evitar estruturas teológicas externas, admitindo prontamente quando as passagens não são claras ou são difíceis para a mente humana finita compreender plenamente. No entanto, assim como um escritor humano pode cometer erros, a IA também pode. É imperativo que o usuário continue a estudar o texto bíblico por si mesmo, reconhecendo a necessidade de estudar não apenas versículos individuais, mas também a Bíblia como um todo.',
    commonThemes: 'Temas Comuns',
    tooltipToggleCommonThemes: 'Mostrar temas comuns de sermões deste capítulo',
    commonThemesTitle: 'Temas Comuns Neste Capítulo',
    translateThemes: 'Traduzir Temas',
    summary: 'Resumo',
    tooltipToggleSummary: 'Mostrar resumo e estatísticas do capítulo',
    summaryTitle: 'Resumo do Capítulo',
    bookSummaryHeading: 'Resumo do Livro',
    chapterSummaryHeading: 'Resumo do Capítulo',
    chapterStatsHeading: 'Estatísticas do Capítulo',
    translateSummary: 'Traduzir Resumo',
    tooltipCopy: 'Copiar para a área de transferência',
    tooltipPrint: 'Imprimir',
    tooltipPdf: 'Baixar como PDF',
    copied: 'Copiado!',
    translateConversation: 'Traduzir Conversa',
    tooltipTranslateConversation: 'Traduzir esta conversa',
    wordDefinitionTitle: (word, verseRef) => `Definição de "${word}" em ${verseRef}`,
    modernDefinitionHeading: 'Definição Moderna',
    originalLangDefinitionHeading: (langWord) => `Língua Original: ${langWord}`,
    archaicUsageNoteHeading: 'Nota sobre Uso Arcaico',
    translateDefinition: 'Traduzir Definição',
    retryGeneration: 'Tentar Novamente',
    simplifyCommentary: 'Simplificar Texto',
    revertCommentary: 'Texto Original',
    tooltipSimplifyCommentary: 'Reescrever este comentário numa linguagem mais simples',
    tooltipRevertCommentary: 'Reverter para o comentário original e mais detalhado',
    crossReferencesHeading: 'Referências Cruzadas',
    crossRefFetchError: 'Não foi possível carregar a referência.',
    showCrossRefs: 'Mostrar Referências',
    hideCrossRefs: 'Ocultar Referências',
    tooltipShowCrossRefs: 'Gerar e mostrar referências cruzadas para este versículo',
    tooltipHideCrossRefs: 'Ocultar as referências cruzadas para este versículo',
    viewReading: 'Leitura',
    tooltipViewReading: 'Visão de leitura padrão',
    viewOutline: 'Esboço',
    tooltipViewOutline: 'Mostrar cabeçalhos do esboço do capítulo',
    viewCommentary: 'Comentário',
    tooltipViewCommentary: 'Mostrar comentário completo para cada versículo',
    viewSimplified: 'Simplificado',
    tooltipViewSimplified: 'Mostrar comentário simplificado para cada versículo',
    moreActions: 'Mais Ações',
    generatingCommentary: 'Gerando comentário',
    generatingCrossRefs: 'Gerando referências cruzadas',
    passageSelection: 'Seleção de Passagem',
    godsWord: "Palavra de Deus",
    view: "Visualizar",
    resources: "Recursos",
    sermonEditor: "Construtor de Esboço de Sermão",
    study: "Estudo",
    sermon: "Sermão",
    sermonBuilder: {
      sermonType: 'Tipo de Sermão',
      sermonTypes: {
        general: 'Sermão Geral',
        expositional: 'Sermão Expositivo',
        textual: 'Sermão Textual',
        topical: 'Sermão Tópico',
      },
      title: 'Título',
      titleTopical: 'Tópico / Título do Sermão',
      bibleText: 'Texto Bíblico',
      bibleTextExpositional: 'Passagem Principal para Exposição',
      bibleTextTextual: 'Texto do Sermão (ex: 1-2 versículos)',
      introduction: 'Introdução',
      thesis: 'Tese (Verdade Principal ou Grande Ideia)',
      thesisExpositional: 'Proposição / Grande Ideia da Passagem',
      thesisTextual: 'Proposição do Texto',
      thesisTopical: 'Proposição / Declaração Principal sobre o Tópico',
      point: 'Ponto de Apoio',
      pointExpositional: 'Ponto Principal da Passagem',
      pointTextual: 'Ponto Principal do Texto',
      pointTopical: 'Ponto Principal sobre o Tópico',
      pointExplanation: 'Explicação',
      scripture: 'Escritura(s) de Apoio',
      illustration: 'Iluminação',
      conclusion: 'Conclusão',
      verdict: 'Veredito (Aplicação, Convite, Apelo)',
      sermonBody: 'Corpo do Sermão',
      sermonBodyDescription: 'Adicione pontos de apoio, escrituras e ilustrações em qualquer ordem.',
      addItem: 'Adicionar Item',
      generateOutline: 'Gerar Esboço',
      generatedOutline: 'Esboço Gerado',
      clearAll: 'Limpar Tudo',
      clearAllConfirmation: {
          title: 'Limpar Campos do Sermão?',
          message: 'Isso apagará todo o conteúdo dos campos do construtor de sermão. Esta ação não pode ser desfeita.',
          confirm: 'Limpar',
          cancel: 'Manter',
      },
      tooltipAddItem: (type: string) => `Adicionar ${type}`,
      tooltipRemoveItem: 'Remover este item',
      tooltipMoveUp: 'Mover item para cima',
      tooltipMoveDown: 'Mover item para baixo',
      fetchAndExpandAll: 'Buscar e expandir todas as referências',
      expandFetchedOnly: 'Incluir apenas textos pré-buscados',
      fetchVerses: 'Buscar Versículos',
      fetchedVerseText: 'Texto do Versículo Buscado',
      disableSermonColors: 'Desativar Cores',
      help: {
        title: 'Guia do Construtor de Esboços de Sermão',
        intro: 'Esta ferramenta ajuda a estruturar seu sermão com base em métodos comuns de pregação. Veja como usá-la:',
        step1: '1. Escolha o Tipo de Sermão: Selecione o estilo de sermão que deseja criar no menu suspenso. "Sermão Geral" é um padrão flexível.',
        step2: '2. Preencha os Campos: Adicione seu título, texto bíblico principal, introdução, pontos-chave e conclusão nos campos correspondentes.',
        step3: '3. Adicione Itens ao Corpo: Use os botões "+ Adicionar Item" para estruturar o corpo do seu sermão com pontos de apoio, referências bíblicas e ilustrações.',
        step4: '4. Gerar Esboço: Quando estiver pronto, clique em "Gerar Esboço". Você pode optar por buscar e incluir automaticamente o texto completo de todas as referências bíblicas em seu esboço.',
        sermonTypesTitle: 'Entendendo os Tipos de Sermão',
        types: {
          general: {
            title: 'Sermão Geral',
            desc: 'Uma estrutura flexível e multifuncional, adequada para a maioria das mensagens.'
          },
          expositional: {
            title: 'Sermão Expositivo',
            desc: 'Deriva seus pontos principais e estrutura diretamente de uma única e maior passagem da Escritura. O objetivo é expor o significado daquele texto específico.'
          },
          textual: {
            title: 'Sermão Textual',
            desc: 'Extrai seus pontos principais de um texto mais curto (geralmente 1-2 versículos). O sermão desenvolve esses pontos, muitas vezes buscando apoio em outras partes da Bíblia.'
          },
          topical: {
            title: 'Sermão Tópico',
            desc: 'Começa com um assunto (ex: Fé, Oração) e usa várias escrituras de toda a Bíblia para explorar esse tópico.'
          }
        }
      }
    },
    wordCounts: 'Contagem de Palavras',
    wordCountFromTranslation: '(da tradução atual)',
    versesSelected: (count: number) => `${count} versículo${count === 1 ? '' : 's'} selecionado${count === 1 ? '' : 's'}`,
    copySelection: 'Copiar Seleção',
    copiedSelection: 'Copiado!',
    deselectAll: 'Desselecionar Tudo',
  },
};

export const GEMINI_SYSTEM_INSTRUCTION = `You are an expert theological study assistant. Your purpose is to provide commentary and answer questions about the Bible based on a strict, conservative, biblicist framework.

Follow these rules unwaveringly:
1.  **Interpretive Method**: Your primary method is grammatical-historical exegesis. All commentary must be grounded in the grammar of the original language texts (Hebrew Masoretic, Greek Textus Receptus) and the immediate and book-level context. Emphasize what the original author intended, as inspired by the Holy Spirit.
2.  **Biblicist Stance**: You must strictly avoid imposing human-made theological systems (e.g., Calvinism, Arminianism) onto the text. Your goal is to explain what the Bible says, and nothing more. Avoid forced interpretations derived from "analogy of faith" where a system dictates meaning.
3.  **Source Distinction**: When providing cultural, historical, or linguistic context (e.g., weights, measures, customs), you MUST clearly distinguish between information derived directly from biblical cross-references and information from external sources. The Bible's interpretation of itself is always the superior and primary source.
4.  **Intellectual Honesty**: If a passage is difficult to interpret, a question cannot be answered definitively from Scripture, or a topic is hard for the finite human mind to fully comprehend, you must state this plainly. Do not speculate or present conjecture as fact.
5.  **Multi-Tiered Commentary & Definitions**: You have several distinct tasks. Keep them separate.
    a. **Primary Commentary**: When asked for verse commentary, your analysis MUST follow all rules above. The commentary text ITSELF MUST NOT discuss or compare the KJV and ACF translations. Your JSON response for this task will contain a 'commentary' field and a boolean 'has_significant_difference' field.
    b. **Translation Difference Explanation**: ONLY when specifically asked to explain a translation difference for a verse, you will provide a detailed, neutral explanation. When explaining a significant translation difference, remain neutral. You must be aware of which ACF version is being used (2011 or 2007). Do not state or imply one version is more correct or that the other is wrong. Instead, explain *why* the translators of the 1769 KJV and the specified ACF version (e.g., "2011 ACF", "2007 ACF") likely made their choices, focusing on what aspect of the original text each translation sought to emphasize.
    c. **Word Definition**: When asked to define a word from a specific verse, provide a JSON object with four fields: 'modern_definition', 'archaic_usage_note', 'original_language_word', and 'original_language_definition'. 'archaic_usage_note' is a nullable string for explaining meaning changes (especially for KJV). **Crucially, if the word is a contronym (a word with opposite meanings), you must explain this phenomenon in the 'archaic_usage_note' after any other notes about archaic usage, and provide other examples of contronyms in that language.** The original language definition should be based on Strong's Concordance.
6.  **View of Scripture**: You must operate from the conviction that the Bible is the pure, perfect, inerrant, and preserved Word of God.
7.  **Science and History**: All answers concerning science and history must be rooted in the Bible as the ultimate authority. Logic, observable science, and proper mathematics are your tools, but they must be subservient to the biblical account.
8.  **Eschatology (Prophecy)**: Your viewpoint on unfulfilled prophecy is futurist and premillennial. Prophecies should be interpreted literally, just as the messianic prophecies of Christ's first coming were fulfilled literally.
9.  **Tone**: Your tone should be scholarly, reverent, and helpful.`;

export const BIBLE_BOOKS: Book[] = [
  { name: 'Genesis', pt_name: 'Gênesis', pt_abbrev: 'gn', chapters: 50 },
  { name: 'Exodus', pt_name: 'Êxodo', pt_abbrev: 'ex', chapters: 40 },
  { name: 'Leviticus', pt_name: 'Levítico', pt_abbrev: 'lv', chapters: 27 },
  { name: 'Numbers', pt_name: 'Números', pt_abbrev: 'nm', chapters: 36 },
  { name: 'Deuteronomy', pt_name: 'Deuteronômio', pt_abbrev: 'dt', chapters: 34 },
  { name: 'Joshua', pt_name: 'Josué', pt_abbrev: 'js', chapters: 24 },
  { name: 'Judges', pt_name: 'Juízes', pt_abbrev: 'jz', chapters: 21 },
  { name: 'Ruth', pt_name: 'Rute', pt_abbrev: 'rt', chapters: 4 },
  { name: '1 Samuel', pt_name: '1 Samuel', pt_abbrev: '1sm', chapters: 31 },
  { name: '2 Samuel', pt_name: '2 Samuel', pt_abbrev: '2sm', chapters: 24 },
  { name: '1 Kings', pt_name: '1 Reis', pt_abbrev: '1rs', chapters: 22 },
  { name: '2 Kings', pt_name: '2 Reis', pt_abbrev: '2rs', chapters: 25 },
  { name: '1 Chronicles', pt_name: '1 Crônicas', pt_abbrev: '1cr', chapters: 29 },
  { name: '2 Chronicles', pt_name: '2 Crônicas', pt_abbrev: '2cr', chapters: 36 },
  { name: 'Ezra', pt_name: 'Esdras', pt_abbrev: 'ed', chapters: 10 },
  { name: 'Nehemiah', pt_name: 'Neemias', pt_abbrev: 'ne', chapters: 13 },
  { name: 'Esther', pt_name: 'Ester', pt_abbrev: 'et', chapters: 10 },
  { name: 'Job', pt_name: 'Jó', pt_abbrev: 'job', chapters: 42 },
  { name: 'Psalms', pt_name: 'Salmos', pt_abbrev: 'sl', chapters: 150 },
  { name: 'Proverbs', pt_name: 'Provérbios', pt_abbrev: 'pv', chapters: 31 },
  { name: 'Ecclesiastes', pt_name: 'Eclesiastes', pt_abbrev: 'ec', chapters: 12 },
  { name: 'Song of Solomon', pt_name: 'Cânticos', pt_abbrev: 'ct', chapters: 8, api_name: 'Song of Songs' },
  { name: 'Isaiah', pt_name: 'Isaías', pt_abbrev: 'is', chapters: 66 },
  { name: 'Jeremiah', pt_name: 'Jeremias', pt_abbrev: 'jr', chapters: 52 },
  { name: 'Lamentations', pt_name: 'Lamentações', pt_abbrev: 'lm', chapters: 5 },
  { name: 'Ezekiel', pt_name: 'Ezequiel', pt_abbrev: 'ez', chapters: 48 },
  { name: 'Daniel', pt_name: 'Daniel', pt_abbrev: 'dn', chapters: 12 },
  { name: 'Hosea', pt_name: 'Oséias', pt_abbrev: 'os', chapters: 14 },
  { name: 'Joel', pt_name: 'Joel', pt_abbrev: 'jl', chapters: 3 },
  { name: 'Amos', pt_name: 'Amós', pt_abbrev: 'am', chapters: 9 },
  { name: 'Obadiah', pt_name: 'Obadias', pt_abbrev: 'ob', chapters: 1 },
  { name: 'Jonah', pt_name: 'Jonas', pt_abbrev: 'jn', chapters: 4 },
  { name: 'Micah', pt_name: 'Miquéias', pt_abbrev: 'mq', chapters: 7 },
  { name: 'Nahum', pt_name: 'Naum', pt_abbrev: 'na', chapters: 3 },
  { name: 'Habakkuk', pt_name: 'Habacuque', pt_abbrev: 'hc', chapters: 3 },
  { name: 'Zephaniah', pt_name: 'Sofonias', pt_abbrev: 'sf', chapters: 3 },
  { name: 'Haggai', pt_name: 'Ageu', pt_abbrev: 'ag', chapters: 2 },
  { name: 'Zechariah', pt_name: 'Zacarias', pt_abbrev: 'zc', chapters: 14 },
  { name: 'Malachi', pt_name: 'Malaquias', pt_abbrev: 'ml', chapters: 4 },
  { name: 'Matthew', pt_name: 'Mateus', pt_abbrev: 'mt', chapters: 28 },
  { name: 'Mark', pt_name: 'Marcos', pt_abbrev: 'mc', chapters: 16 },
  { name: 'Luke', pt_name: 'Lucas', pt_abbrev: 'lc', chapters: 24 },
  { name: 'John', pt_name: 'João', pt_abbrev: 'jo', chapters: 21 },
  { name: 'Acts', pt_name: 'Atos', pt_abbrev: 'atos', chapters: 28 },
  { name: 'Romans', pt_name: 'Romanos', pt_abbrev: 'rm', chapters: 16 },
  { name: '1 Corinthians', pt_name: '1 Coríntios', pt_abbrev: '1co', chapters: 16 },
  { name: '2 Corinthians', pt_name: '2 Coríntios', pt_abbrev: '2co', chapters: 13 },
  { name: 'Galatians', pt_name: 'Gálatas', pt_abbrev: 'gl', chapters: 6 },
  { name: 'Ephesians', pt_name: 'Efésios', pt_abbrev: 'ef', chapters: 6 },
  { name: 'Philippians', pt_name: 'Filipenses', pt_abbrev: 'fp', chapters: 4 },
  { name: 'Colossians', pt_name: 'Colossenses', pt_abbrev: 'cl', chapters: 4 },
  { name: '1 Thessalonians', pt_name: '1 Tessalonicenses', pt_abbrev: '1ts', chapters: 5 },
  { name: '2 Thessalonians', pt_name: '2 Tessalonicenses', pt_abbrev: '2ts', chapters: 3 },
  { name: '1 Timothy', pt_name: '1 Timóteo', pt_abbrev: '1tm', chapters: 6 },
  { name: '2 Timothy', pt_name: '2 Timóteo', pt_abbrev: '2tm', chapters: 4 },
  { name: 'Titus', pt_name: 'Tito', pt_abbrev: 'tt', chapters: 3 },
  { name: 'Philemon', pt_name: 'Filemom', pt_abbrev: 'fm', chapters: 1 },
  { name: 'Hebrews', pt_name: 'Hebreus', pt_abbrev: 'hb', chapters: 13 },
  { name: 'James', pt_name: 'Tiago', pt_abbrev: 'tg', chapters: 5 },
  { name: '1 Peter', pt_name: '1 Pedro', pt_abbrev: '1pe', chapters: 5 },
  { name: '2 Peter', pt_name: '2 Pedro', pt_abbrev: '2pe', chapters: 3 },
  { name: '1 John', pt_name: '1 João', pt_abbrev: '1jo', chapters: 5 },
  { name: '2 John', pt_name: '2 João', pt_abbrev: '2jo', chapters: 1 },
  { name: '3 John', pt_name: '3 João', pt_abbrev: '3jo', chapters: 1 },
  { name: 'Jude', pt_name: 'Judas', pt_abbrev: 'jd', chapters: 1 },
  { name: 'Revelation', pt_name: 'Apocalipse', pt_abbrev: 'ap', chapters: 22 },
];